version: 2
jobs:
  build:
    name: Build
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}

      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}

      - save_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

  test:
    name: Tests
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: npm run lint

  publish_canary:
    name: Deploy
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish --tag canary --access=public

  publish:
    name: Deploy
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm dist-tag add `npm view . name`@`node -p "require('./package.json').version"` latest

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish_canary:
          requires:
            - test
          filters:
            branches:
              only: master
      - publish:
          requires:
            - test
          filters:
            branches:
              only: production
